version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails-app:/app
    ports:
      - "3000:3000"
    user: ${CURRENT_UID}
    depends_on:
      - db
